name: Secure Deployment Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para análisis completo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usa la versión recomendada de Node.js

      - name: Install dependencies
        run: npm install

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.2  # Versión correcta
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=tu_proyecto
            -Dsonar.organization=tu_organizacion
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,tests/**
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  unit-tests:
    needs: sonarqube-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test -- --coverage  # Genera cobertura para SonarQube

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov.info

  security-checks:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run static analysis (Lint)
        run: npm run lint

      - name: Check for vulnerable dependencies
        run: npm audit --audit-level=critical  # Solo falla con vulnerabilidades críticas

  deploy:
    needs: security-checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: echo "Deployment to production would happen here"
